<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
        </style>
    </head>
    <body>
        <h1>New Client</h1>
        <div>XWeb Human Emulator</div>

        <?php if (isset($name)) : ?>
            <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
        <?php else: ?>
            <h6>Hello, Dolly</h6>
        <?php endif; ?>
        <hr><br>
        <form method="POST">
            <p><input type="radio" id="clientChoice1" checked name="clientRt" value="1"><label for="clientChoice1">Xweb RT Client</label></p>
            
            <p><input type="radio" id="clientChoice2" name="clientRt" value="0"><label for="clientChoice2">Xweb Client</label></p>
            <input name="inTray" type="hidden" value="false" />

            <p><input type="checkbox" name="inTray" checked value="true"><label for="trayChoice">In Tray?</label></p>
            <label for="scriptChoice">Script Name</label>
            <p><input type="text" id="scriptChoice" name="scriptName" value="init.php"></p>



            <p><input type="hidden" name="profileId" value="1"></p>
            <p><input type="hidden" name="pid" value="4"></p>
            <p><textarea name="message"></textarea></p>

            <p><input type="submit"></p>
        </form>
    </body>
</html>
